# Generated by Django 4.0.3 on 2022-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_restaurantnotifications_notifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantnotifications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
