# Generated by Django 4.0.3 on 2022-03-15 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_restaurantnotifications_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantnotifications',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
