# Generated by Django 4.0.3 on 2022-03-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_options_alter_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
