# Generated by Django 4.0.3 on 2022-03-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='posted',
            new_name='date',
        ),
    ]
