# Generated by Django 4.0.3 on 2022-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_abstractimage_image_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='logos/python.png', upload_to='logos/'),
        ),
    ]
